# Generated by Django 2.0.4 on 2018-04-26 18:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ramo_atuacao', models.CharField(choices=[('A', 'Alimentos'), ('Auto', 'Automóveis'), ('Esp', 'Esport')], max_length=4)),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('slug', models.SlugField(verbose_name='Slug')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('contato', models.IntegerField(max_length=11, validators=[django.core.validators.RegexValidator('^\\d+$')], verbose_name='Contato')),
            ],
            options={
                'verbose_name': 'Store',
                'verbose_name_plural': 'Stores',
                'ordering': ['nome'],
            },
        ),
    ]
