# Generated by Django 2.0.4 on 2018-04-26 18:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='contato',
            field=models.IntegerField(validators=[django.core.validators.RegexValidator('^\\d+$')], verbose_name='Contato'),
        ),
    ]
