# Generated by Django 2.0.4 on 2018-04-26 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180426_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='ramo_atuacao',
            field=models.CharField(choices=[('Alimentos', 'Alimentos'), ('Automoveis', 'Automóveis'), ('Esporte', 'Esporte')], default='Alimentos', max_length=10),
        ),
    ]
