# Generated by Django 2.0.4 on 2018-04-27 03:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180426_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='contato',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^\\d+$')], verbose_name='Contato'),
        ),
    ]
